### PR TITLE
Adding Feature/ptbr support

### PR DESCRIPTION
**Pull request by Ryojikn**
I've added Ptbr support which consists of minor changes to Portuguese from Portugal, such as:

"Quatorze" > "Catorze"
"Dezanove" > "Dezenove"
"Dezasseis" > "Dezesseis",

Also updated unit tests and readme, as well as setup.py description.
For all my tests, works even better with ptbr than default portuguese due to those minor differences in language.

### CODE REVIEW

**Comment by rtxm** [comment]
Thank you very much for your contribution!

We prefer to handle variations of a given language in the same language module instead of creating a "new" language (it's the same language after all), so that the same class and language code can process all variants. 
Otherwise, that's a lot a copy paste, isn't it?

Adding variants to a language is quite easy, look at the `french` module:

```python
# Variants
MTENS["quatre-vingt"] = 80
MTENS["octante"] = 80
```
Or even in the `portuguese` module that already handles variant "um/uma", "dois/duas", …

So, in `portuguese.py` just add something like:

```python
STEN["catorze"] = 14
STEN["dezesseis"] = 16
# etc…
```
and don't forget to add them to `AND_NUMS` too.

You should be able to add variants for the ordinals too if needed.

Don't hesitate to ask for help if you have any question.

**Review by Ryojikn — COMMENTED** [review]
Changes have been made to consider Portuguese as a single language.

This will solve for both languages pt and ptbr, due to small linguistic changes.

Also added support for more multipliers

**Comment by rtxm** [comment]
Thank you! The PR is much more compact :wink:

Please add some unit tests in Brazilian Portuguese as examples and to ensure they are correctly "understood", and your PR will be perfect!

**Comment by joaoalvarenga** [comment]
Is there anyone working on this PR, can I work on this PR?

**Pull request merged**
